# Generated by Django 3.1.5 on 2021-01-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='city',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='country',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('Potential', 'Potential'), ('Prospect', 'Prospect'), ('Negotiation', 'Negotiation'), ('Converted', 'Converted'), ('Failed', 'Failed')], max_length=15, null=True),
        ),
    ]
