# Generated by Django 3.1.5 on 2021-01-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20210124_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
