# Generated by Django 3.1.5 on 2021-01-28 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_auto_20210128_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='avatar',
            field=models.ImageField(null=True, upload_to='media/avatar'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='LeadDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, upload_to='media/files')),
                ('tasks', models.TextField(max_length=1000)),
                ('Lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
            ],
        ),
    ]
