# Generated by Django 3.1.5 on 2021-01-28 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_auto_20210128_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='avatar',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='leaddetail',
            name='Lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.lead'),
        ),
        migrations.AlterField(
            model_name='leaddetail',
            name='files',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
